# Generated by Django 3.1.5 on 2021-01-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=20)),
                ('option_2', models.CharField(max_length=20)),
                ('option_3', models.CharField(max_length=20)),
                ('option_4', models.CharField(max_length=20)),
                ('right_ans', models.CharField(max_length=20)),
            ],
        ),
    ]
